<?php

$applications = $block->getJobApplication();
?>
<div class="preview">
<label><b>Name:</b></label>
<p><?= $block->escapeHtmlAttr(__($applications[0]['applicant_name'])) ?></p>
<br>
<label><b>Address:</b></label>
<p><?= $block->escapeHtmlAttr(__($applications[0]['address'])) ?></p>
<br>
<label><b>Phone Number:</b></label>
<p><?= $block->escapeHtmlAttr(__($applications[0]['phone_number'])) ?></p>
<br>
<label><b>Job Designation:</b></label>
<p><?= $block->escapeHtmlAttr(__($applications[0]['job_designation']))?></p>
<br>
<label><b>Experience:</b></label>
<p><?= $block->escapeHtmlAttr(__($applications[0]['experience']))?></p>
<br>
<label><b>Cover Letter:</b></label>
<p><?= $block->escapeHtmlAttr(__($applications[0]['cover_letter'])) ?></p>
<br>
<label><b>Resume:</b></label>
<p><?=/* @noEscape */$block->getResume();?></p>
</div>

<style>
.preview{
    width: 98%;
    margin: auto;
    font-size: 110%;
}
</style>