<?php 
 $log = $block->getuserStatus();
if ($log) {
    $customerName = $block->getCustomerData()->getFirstName()." ".$block->getCustomerData()->getLastName();
    $customerEmail = $block->getCustomerData()->getEmail();
}
 ?>


<form action="<?php echo $block->getSubmitUrl() ?> " method="POST" enctype="multipart/form-data" data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill your details')) ?></span></legend>
        <fieldset class="fieldset row">
            <div class="fields col-md-6">
                <div class="field name required">
                    <label class="label" for="applicant_name">
                        <span><?= $block->escapeHtmlAttr(__('Name'))?></span>
                    </label>
                    <div class="control">
                        <input name="applicant_name" id="applicant_name" title="name" 
                               value="<?php echo $log ? $customerName: ""?>"
                               class="input-text required-entry" type="text"  data-validate="{required:true}" required  />
                    </div>
                </div>
                <div class="field name required">
                    <label class="label" for="email">
                        <span><?= $block->escapeHtmlAttr(__('Email')) ?></span>
                    </label>
                    <div class="control">
                        <input name="email" id="email" title="Email"
                               value="<?php echo $log ? $customerEmail: ""?>"
                               class="input-text" type="email"
                               data-validate="{required:true, 'validate-email':true}" required/>
                    </div>
                </div>
                <div class="field name required">
                    <label class="label" for="address">
                        <span><?= $block->escapeHtmlAttr(__('Address')) ?></span>
                    </label>
                    <div class="control">
                        <textarea name="address" id="address" title="Address"
                               data-validate="{required:true}" required ></textarea>
                    </div>
                </div>

                <div class="field name required">
                    <label class="label" for="number">
                        <span><?= $block->escapeHtmlAttr(__('Phone Number')) ?></span>
                    </label>
                    <div class="control">
                        <input name="phone_number" id="phone_number" title="Phone Number"
                               class="input-text" type="number"
                               data-validate="{required:true}" required/>
                    </div>
                </div>

                <div class="field name required">
                    <label class="label" for="experience">
                        <span><?= $block->escapeHtmlAttr(__('Experience (in years)')) ?></span>
                    </label>
                    <div class="control">
                        <input name="experience" id="experience" title="Experience"
                               class="input-text" type="number"
                               data-validate="{required:true}" required/>
                    </div>
                </div>

                <div class="field name required">
                    <label class="label" for="cover_letter">
                        <span><?= $block->escapeHtmlAttr(__('Cover Letter')) ?></span>
                    </label>
                    <div class="control">
                            <textarea name="cover_letter" id="cover_letter" title="Cover Letter" value="" class="input-text" type="text" data-validate="{required:true}" required></textarea>
                        </div>
                </div>

                <div class="field name required">
                    <label class="label" for="resume">
                        <span><strong><?= $block->escapeHtmlAttr(__('Upload Resume:')) ?><strong></span>
                    </label>
                    <input type="file" name="resume" id="resume" title="Upload Custom File" class="input-text required" data-validate="{'required-file':true}" data-validate="{'validate-forbidden-extensions':true}" data-validation-params="pdf" required>
                </div>
            </div>
            <p id="warning" style="display:none;color:red;">Disallowed File type</p>
            <input type="hidden" id="job_designation" name="job_designation" value="<?php echo $block->getJobName()?>">
            
        </fieldset>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" id="save" class="action submit primary" title="Save">
                <span><?= $block->escapeHtmlAttr(__('Save')) ?></span>
            </button>
        </div>
    </div>
</form>


<script>
    

window.onload = function () {
    document.getElementById("resume").onchange = function () {
        let fileName = this.value;
        let lastChar = fileName.substr(fileName.length - 3); 
        if(lastChar != 'pdf'){
            document.getElementById("warning").style.display = "block";    
            document.getElementById('save').disabled = true;
        }
        else{
            document.getElementById("warning").style.display = "none";    
            document.getElementById('save').disabled = false;
        }
    };
};
</script>