<?php

$content = $block->getJobCollection()[0]['detailed_job_description'];
$detailedDescription = $block->processContent($content);?>
<h1><?php echo $block->getJobCollection()[0]['job_designation']?></h1>
<div>
    <?php echo $detailedDescription ?>
</div>
<div> 
    <button style="background-color: #1979c3; color: #ffffff;" onclick="location.href='<?php echo $block->getButtonUrl() ?>'" >Apply Now</button>
</div>


            
          