<link rel='stylesheet' href='<?php echo $block->getViewFileUrl("Terrificminds_CareerPageBuilder::css/career.css") ?>' />
<div class="container">
<?php 
$categoryCollection = $block->getCategoryCollection();
foreach ($categoryCollection as $category) {
  $categoryId = $category->getId();
  if ($categoryId != 1) {
    ?>
<button class="accordion"><?php echo $category->getCategoryName() ?></button>
<div class="panel">
<?php
        $jobCollection = $block->getJobCollection($categoryId);
        foreach ($jobCollection as $job) {
          $postedDate = $job->getCreatedAt();
          $newDate = date("d-m-Y", strtotime($postedDate));  
          ?>
         <h3><a href="maincareerspage/index/index?jobId=<?php echo $job->getJobId() ?>"></b><?php echo $job->getJobDesignation(); ?></a></h3>
         <p>Posted : <?php echo $newDate ?></p>
         <p><?php echo $job->getSmallJobDescription() ?></p>
         
<?php
        } ?>
</div>
<?php }
} ?>
</div>



<script>
var acc = document.getElementsByClassName("accordion");
var i;
for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}
</script>




