<link rel='stylesheet'
href='<?= /* @noEscape */$block->getViewFileUrl("Terrificminds_CareerPageBuilder::css/career.css")?>' />
<div class="container" style="display:<?= /* @noEscape */ $block->config()?>;">
<h2 style="display:<?= /* @noEscape */ $block->checkTitle()?>;"><?= $block->escapeHtml($block->getData('title')) ?></h2>
<?php
$categoryCollection = $block->getCategoryCollection();
foreach ($categoryCollection as $category) {
    $categoryId = $category->getId();
    if ($categoryId != 1) {
        ?>
<button class="accordion"><?= /* @noEscape */ $category->getCategoryName()?></button>
<div class="panel">
        <?php
        $jobCollection = $block->getJobCollection($categoryId);
        foreach ($jobCollection as $job) {
            $postedDate = $job->getCreatedAt();
            $newDate = date("d-m-Y", strtotime($postedDate));
            ?>
         <h3><a href="<?= /* @noEscape */ $block->buildUrl($job->getJobId()) ?>">
         </b><?=/* @noEscape */$job->getJobDesignation(); ?></a></h3>
         <p><i>Posted: <?=$block->escapeHtmlAttr($newDate)?></i></p>
         <p><?= /* @noEscape */ $job->getSmallJobDescription() ?></p>
            <?php
        } ?>
</div>
  <?php }
} ?>
</div>
<script>
var acc = document.getElementsByClassName("accordion");
var i;
for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}
</script>




