<?php
$categoryCollection = $block->categoryCollection();
$jobCollection = $block->jobCollection();

?>

<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc; 
}

.panel {
  padding: 0 18px;
  display: none;
  background-color: white;
  overflow: hidden;
}
</style>


<h2>Careers</h2>
<?php 
foreach ($categoryCollection as $category) {
        $name = $category->getCategoryName();
        $categoryId  = $category->getId()
?>

<button class="accordion"><?php echo $name ?></button>
<div class="panel">
<?php 

$filteredCollection = $jobCollection->addFieldToFilter('category_id', $categoryId);
foreach ($filteredCollection as $job) {
        $name = $job->getJobDesignation();
            $description = $job->getSmallJobDescription();
?>
    <p></b><?php echo $name ?></p>
    <p><?php echo $description ?></p>
    <hr/>
<?php } ?>
</div>

<?php } ?>


<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}
</script>

</body>
</html>


